import test from 'node:test'
import assert from 'node:assert/strict'
import {createRequire} from 'node:module'
import {pdfPendencias,csvPendencias,resumoPendencias} from '../src/lib/relatorioOperacao.js'
import {permissoesPendencia} from '../src/lib/pendencias.js'
const require=createRequire(import.meta.url),{permissoes,transicao}=require('../functions/pendenciaPolitica'),{podeOperar}=require('../functions/operacaoPolitica')
const ordem={estado:'liberada',feiraId:'f',produtorIds:['p'],atendimentoIds:['c'],equipeIds:['e'],revisao:1},p=(papel,uid='u')=>({papel,uid,ativo:true,feiraIds:['f'],equipeIds:['e']}),a={autor:'u',equipeId:'e',especialidade:'mobiliario',status:'em_execucao',revisao:1}
test('produtor e atendimento exigem atribuição individual ao estande',()=>{assert.ok(podeOperar(p('produtor','p'),ordem));assert.ok(!podeOperar(p('produtor'),ordem));assert.ok(podeOperar(p('atendimento_comercial','c'),ordem));assert.ok(!podeOperar(p('atendimento_comercial'),ordem))})
test('atendimento aprova chamados, mas não executa; analista de projeto só orienta',()=>{const c=p('atendimento_comercial','c');assert.ok(permissoes(c,ordem).aprovar);assert.ok(!permissoes(c,ordem,a).executar);assert.throws(()=>transicao(c,ordem,a,'aguardando_validacao'));assert.ok(permissoes(p('analista_projeto'),ordem).anotar);assert.ok(!permissoes(p('analista_projeto'),ordem).criar)})
test('mobiliário e CV executam apenas serviços da sua especialidade',()=>{assert.ok(permissoes(p('mobiliario'),ordem,a).executar);assert.ok(!permissoes(p('mobiliario'),ordem,{...a,especialidade:'eletrica'}).executar);assert.ok(!permissoes(p('analista_cv'),ordem,a).executar)})
test('execução segue para validação; apenas gestão valida/reabre com motivo',()=>{assert.equal(transicao(p('produtor','p'),ordem,a,'aguardando_validacao'),'aguardando_validacao');assert.equal(transicao(p('produtor','p'),ordem,a,'aguardando_validacao','',true),'concluida');const pronta={...a,status:'aguardando_validacao'};assert.throws(()=>transicao(p('produtor','p'),ordem,pronta,'concluida'));assert.equal(transicao(p('gerente_operacional'),ordem,pronta,'concluida'),'concluida');assert.throws(()=>transicao(p('gerente_operacional'),ordem,pronta,'aberta'));assert.equal(transicao(p('gerente_operacional'),ordem,pronta,'aberta','Falta ajustar'),'aberta');assert.throws(()=>transicao(p('admin'),{...ordem,revisao:2},pronta,'concluida'))})
test('permissões da interface acompanham o servidor para cada função autorizada',()=>{for(const [papel,uid] of [['admin','u'],['gerente_operacional','u'],['analista_operacional','u'],['produtor','p'],['atendimento_comercial','c'],['mobiliario','u'],['analista_cv','u'],['analista_projeto','u'],['equipe_producao','u']]){const u=p(papel,uid),server=permissoes(u,ordem,a),ui=permissoesPendencia(u,ordem,a);for(const k of Object.keys(ui))assert.equal(ui[k],server[k],papel+':'+k)}})
test('relatório credita executor, separa validador e protege CSV de fórmulas',async()=>{const linhas=[{clienteNome:'Empresa',feira:'Feira',descricao:'=1+1',status:'concluida',executadoNome:'Produtor',validadoNome:'Gerente',equipeNome:'Equipe',notaExecucao:'Ajustado',revisao:1},{status:'aguardando_validacao',executadoNome:'Outro'}];assert.deepEqual(resumoPendencias(linhas).executores,{Produtor:1});assert.match(csvPendencias(linhas),/"'=1\+1"/);const pdf=await pdfPendencias(linhas);assert.ok(pdf.size>1000);assert.match(await pdf.slice(0,5).text(),/^%PDF-/)})
