import { useEffect,useMemo,useState } from 'react'
import { collection,getDocs,query,where,orderBy,limit } from 'firebase/firestore'
import { db } from '../lib/firebase.js'
import { analisarUso } from '../lib/analiseUso.js'

export default function AnaliseUso(){
  const [dados,setDados]=useState([]),[dias,setDias]=useState(30),[modelo,setModelo]=useState(''),[erro,setErro]=useState(''),[carregando,setCarregando]=useState(true),[modelos,setModelos]=useState([]),[usuarios,setUsuarios]=useState([]),[versao,setVersao]=useState(0)
  useEffect(()=>{let vivo=true;setCarregando(true);setErro('');Promise.all([
    getDocs(query(collection(db,'sessoesUso'),where('atualizadoEm','>=',new Date(Date.now()-dias*86400000)),orderBy('atualizadoEm','desc'),limit(1000))),getDocs(collection(db,'modelos')),getDocs(collection(db,'usuarios'))
  ]).then(([s,m,u])=>{if(vivo){setDados(s.docs.map(d=>({id:d.id,...d.data()})));setModelos(m.docs.map(d=>({id:d.id,...d.data()})));setUsuarios(u.docs.map(d=>({id:d.id,...d.data()})))}}).catch(()=>vivo&&setErro('Não foi possível consultar as métricas. Confira conexão e permissões.')).finally(()=>vivo&&setCarregando(false));return()=>{vivo=false}},[dias,versao])
  const filtradas=useMemo(()=>dados.filter(s=>!modelo||s.modeloId===modelo),[dados,modelo]),resumo=useMemo(()=>analisarUso(filtradas),[filtradas])
  return <div className="admin-pagina"><header className="admin-cabecalho"><p className="admin-eyebrow">MELHORIA CONTÍNUA</p><h1>Entenda a experiência.</h1><p>Encontre sinais de dificuldade e escolha o que testar com os expositores.</p></header>
    <div className="admin-filtros"><label>Período<select className="select" value={dias} onChange={e=>setDias(Number(e.target.value))}>{[7,30,90].map(n=><option key={n} value={n}>{n} dias</option>)}</select></label><label>Projeto<select className="select" value={modelo} onChange={e=>setModelo(e.target.value)}><option value="">Todos os projetos</option>{modelos.map(m=><option value={m.id} key={m.id}>{m.nome}</option>)}</select></label><button className="btn" onClick={()=>setVersao(v=>v+1)}>Atualizar</button></div>
    {erro&&<p role="alert" className="erro-inline">{erro}</p>}{carregando?<p role="status">Consultando sessões…</p>:<>
    <div className="admin-indicadores">{[['Sessões observadas',resumo.total],['Expositores distintos',resumo.usuarios],['Sessões com envio',resumo.enviadas],['Tempo ativo mediano',`${Math.round(resumo.mediana/60)} min`]].map(([n,v])=><article className="card card-pad" key={n}><span>{n}</span><strong>{v}</strong></article>)}</div>
    {!dados.length&&<p className="orientacao">Ainda não há dados. As métricas começam com os próximos acessos de clientes; testes do admin não entram nesta análise.</p>}
    <p className="dim">{dados.length===1000?'Amostra limitada às 1.000 sessões mais recentes do período. ':''}Tempo ativo exclui abas ocultas e inatividade acima de 60 segundos. “Sem envio” indica a última etapa de sessões sem atualização há mais de 30 minutos; não prova abandono definitivo.</p>
    <div className="admin-tabela"><table><thead><tr><th>Etapa</th><th>Sessões</th><th>Concluíram</th><th>Sem envio</th><th>Com erro</th><th>Retornos</th><th>Mediana ativa</th><th>Atenção</th></tr></thead><tbody>{resumo.etapas.map(e=><tr key={e.id}><td>{e.nome}</td><td>{e.visitas}</td><td>{e.concluidas}</td><td>{e.semEnvio}</td><td>{e.erros}</td><td>{e.repetidas}</td><td>{Math.round(e.tempo)} s</td><td>{e.score==null?'Poucos dados':`${e.score}/100`}</td></tr>)}</tbody></table></div>
    <section className="card card-pad"><h2>O que investigar primeiro</h2>{resumo.sugestoes.length?resumo.sugestoes.map(s=><p key={s.etapa}><b>{s.etapa} · {s.score}/100:</b> {s.texto}</p>):<p>Ainda não há um sinal consistente de gargalo. Reúna mais sessões e observe testes com usuários.</p>}<details><summary>Como são calculadas as sugestões</summary><p>Heurística transparente, não diagnóstico automático: 50% de peso para sessões paradas sem envio, 30% para sessões com erro e 20% para mais de dois acessos à mesma etapa. Só calcula com pelo menos cinco sessões por etapa. Acima de 20 pontos, sugere uma investigação. Comparações por projeto ajudam a separar dificuldade da interface de complexidade do estande.</p></details></section>
    <section className="card card-pad"><h2>Últimas sessões</h2><p className="dim">Identificação restrita à equipe administrativa. Não são coletadas senhas, artes, texto digitado ou gravações da tela.</p>{filtradas.slice(0,30).map(s=><p key={s.id}><b>{usuarios.find(u=>u.id===s.uid)?.nome||'Expositor'}</b> · {modelos.find(m=>m.id===s.modeloId)?.nome||'Projeto'} · {s.dispositivo} · {s.enviou?'Enviou proposta':`Última etapa: ${resumo.etapas.find(e=>e.id===s.ultimaEtapa)?.nome||'carregamento'}`} · {s.acoes?.cliques_repetidos||0} sequências de cliques repetidos · {s.acoes?.reinicio||0} reinícios · {(s.acoes?.glb_erro||0)+(s.acoes?.upload_erro||0)+(s.acoes?.envio_erro||0)} erros</p>)}</section></>}
  </div>
}
