import {useEffect,useState} from 'react'
import {useAuth} from '../store/AuthContext.jsx'
import {operacao,ehGestor,ESPECIALIDADES,PAPEIS_OPERACIONAIS} from '../lib/operacao.js'
import AnexosOperacionais from '../components/AnexosOperacionais.jsx'
const vazio={nome:'',especialidade:'montagem',feiraIds:[],membros:[],responsavelUid:'',responsavelNome:'',contato:'',instrucoes:'',ativo:true}
function MarcarLista({lista,selecionados,aoMudar}){return <div className="operacao-selecao">{lista.map(x=><label className="operacao-check" key={x.id}><input type="checkbox" checked={selecionados.includes(x.id)} onChange={e=>aoMudar(e.target.checked?[...selecionados,x.id]:selecionados.filter(id=>id!==x.id))}/>{x.nome}</label>)}</div>}
export default function EquipesOperacionais(){
  const {perfil}=useAuth(),[dados,setDados]=useState({equipes:[],feiras:[],usuarios:[]}),[f,setF]=useState(vazio),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false),[convite,setConvite]=useState(''),[acesso,setAcesso]=useState({nome:'',email:'',papel:'analista_operacional',feiraIds:[],ativo:true})
  const carregar=async()=>{try{setDados(await operacao({acao:'listar'}))}catch(e){setErro(e.message)}}
  useEffect(()=>{carregar()},[])
  async function salvar(e){e.preventDefault();setOcupado(true);setErro('');try{await operacao({acao:'equipe',...f});setF(vazio);await carregar()}catch(e){setErro(e.message)}finally{setOcupado(false)}}
  return <div className="admin-pagina operacao-pagina"><header className="admin-cabecalho"><span className="admin-eyebrow">USET · OPERAÇÃO</span><h1>Equipes e responsáveis</h1><p>Distribua o trabalho por feira e mantenha as instruções e documentos junto de cada equipe.</p></header>{erro&&<p role="alert">{erro}</p>}
    <div className="operacao-grid"><section className="col">{dados.equipes.map(eq=><article key={eq.id} className="card card-pad"><h2>{eq.nome}</h2><p>{ESPECIALIDADES[eq.especialidade]} · {eq.ativo?'Ativa':'Inativa'}</p><p>{eq.responsavelNome||dados.usuarios.find(u=>u.uid===eq.responsavelUid)?.nome||'Responsável a definir'} {eq.contato}</p><p>{eq.feiraIds.map(id=>dados.feiras.find(f=>f.id===id)?.nome||id).join(' · ')}</p><p>{eq.instrucoes}</p>{ehGestor(perfil)&&<button className="btn" onClick={()=>setF({...vazio,...eq})}>Editar equipe</button>}<AnexosOperacionais tipo="equipesOperacionais" parentId={eq.id} podeEnviar={ehGestor(perfil)} podeRemover={ehGestor(perfil)}/></article>)}{!dados.equipes.length&&<p>Nenhuma equipe cadastrada nas suas feiras.</p>}</section>
    {ehGestor(perfil)&&<form className="card card-pad col" onSubmit={salvar}><h2>{f.id?'Editar equipe':'Cadastrar equipe'}</h2><label>Nome da equipe<input className="input" required maxLength={180} value={f.nome} onChange={e=>setF({...f,nome:e.target.value})}/></label><label>Especialidade<select className="select" value={f.especialidade} onChange={e=>setF({...f,especialidade:e.target.value})}>{Object.entries(ESPECIALIDADES).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label><fieldset><legend>Feiras atendidas</legend><MarcarLista lista={dados.feiras} selecionados={f.feiraIds} aoMudar={feiraIds=>setF({...f,feiraIds})}/></fieldset><fieldset><legend>Integrantes com acesso ao app</legend><MarcarLista lista={dados.usuarios.filter(u=>f.feiraIds.every(id=>u.feiraIds.includes(id))).map(u=>({id:u.uid,nome:u.nome}))} selecionados={f.membros} aoMudar={membros=>setF({...f,membros,responsavelUid:membros.includes(f.responsavelUid)?f.responsavelUid:''})}/></fieldset><label>Responsável com acesso<select className="select" value={f.responsavelUid||''} onChange={e=>setF({...f,responsavelUid:e.target.value})}><option value="">A definir</option>{dados.usuarios.filter(u=>f.membros.includes(u.uid)).map(u=><option key={u.uid} value={u.uid}>{u.nome}</option>)}</select></label><label>Nome do encarregado / contato externo<input className="input" value={f.responsavelNome} onChange={e=>setF({...f,responsavelNome:e.target.value})}/></label><label>Telefone<input className="input" value={f.contato} onChange={e=>setF({...f,contato:e.target.value})}/></label><label>Instruções<textarea className="input" maxLength={4000} value={f.instrucoes} onChange={e=>setF({...f,instrucoes:e.target.value})}/></label><label className="operacao-check"><input type="checkbox" checked={f.ativo} onChange={e=>setF({...f,ativo:e.target.checked})}/>Equipe ativa</label><button className="btn btn-primary" disabled={ocupado}>Salvar equipe</button>{f.id&&<button type="button" className="btn" onClick={()=>setF(vazio)}>Cancelar edição</button>}</form>}</div>
    {perfil.papel==='admin'&&<form className="card card-pad operacao-acesso" onSubmit={async e=>{e.preventDefault();setOcupado(true);setErro('');setConvite('');try{const r=await operacao({acao:'cadastroAcesso',...acesso});setConvite(r.convite);await carregar()}catch(ex){setErro(ex.message)}finally{setOcupado(false)}}}><h2>Acessos da operação</h2><p>Cadastre a pessoa antes de incluí-la na equipe. A integração de e-mail permanece pendente; copie o convite para definir a senha.</p><label>Nome<input className="input" required value={acesso.nome} onChange={e=>setAcesso({...acesso,nome:e.target.value})}/></label><label>E-mail<input className="input" type="email" required value={acesso.email} onChange={e=>setAcesso({...acesso,email:e.target.value})}/></label><label>Perfil<select className="select" value={acesso.papel} onChange={e=>setAcesso({...acesso,papel:e.target.value})}>{Object.entries(PAPEIS_OPERACIONAIS).map(([id,n])=><option value={id} key={id}>{n}</option>)}</select></label><fieldset><legend>Feiras permitidas</legend><MarcarLista lista={dados.feiras} selecionados={acesso.feiraIds} aoMudar={feiraIds=>setAcesso({...acesso,feiraIds})}/></fieldset><label className="operacao-check"><input type="checkbox" checked={acesso.ativo!==false} onChange={e=>setAcesso({...acesso,ativo:e.target.checked})}/>Acesso ativo</label><button className="btn btn-primary" disabled={ocupado}>Cadastrar / atualizar acesso</button>{convite&&<button type="button" className="btn" onClick={async()=>{try{await navigator.clipboard.writeText(convite)}catch{setErro('Não foi possível copiar o convite neste navegador.')}}}>Copiar convite de acesso</button>}<div className="operacao-selecao">{dados.usuarios.map(u=><button type="button" className="btn" key={u.uid} onClick={()=>setAcesso({nome:u.nome,email:u.email,papel:u.papel,feiraIds:u.feiraIds,ativo:u.ativo!==false})}>{u.nome} · {PAPEIS_OPERACIONAIS[u.papel]}{u.ativo===false?' · acesso desativado':''}</button>)}</div></form>}
  </div>
}
