import {useEffect,useState} from 'react'
import {Link,useNavigate} from 'react-router-dom'
import {collection,onSnapshot,query,where,orderBy,limit,startAfter,getDocs} from 'firebase/firestore'
import {db} from '../lib/firebase.js'
import {useAuth} from '../store/AuthContext.jsx'
import {executarComercial} from '../lib/comercial.js'
import {ativarPush,desativarPush,restaurarPush,suportaPush} from '../lib/push.js'
function useAvisos(){const {user,perfil}=useAuth(),[lista,setLista]=useState([]),[erro,setErro]=useState('');useEffect(()=>{setLista([]);if(!user||!perfil||perfil.ativo===false)return;return onSnapshot(query(collection(db,'notificacoes'),where('destinatario','==',user.uid),orderBy('criadoEm','desc'),limit(100)),s=>setLista(s.docs.map(d=>({id:d.id,...d.data()}))),e=>setErro(e.message))},[user?.uid,perfil?.ativo]);return{lista,erro}}
export function SinoNotificacoes(){const {lista}=useAvisos(),{user,perfil}=useAuth();useEffect(()=>{if(user&&perfil?.ativo!==false&&!perfil?.precisaTrocarSenha)restaurarPush().catch(()=>{})},[user?.uid,perfil?.ativo,perfil?.precisaTrocarSenha]);const n=lista.filter(n=>!n.lida).length;return <Link className="btn btn-ghost btn-sm" to="/notificacoes" aria-label={`Notificações${n?`, ${n} não lidas`:''}`}>Avisos {n>0&&<span className="tag">{n===100?'99+':n}</span>}</Link>}
export default function Notificacoes(){const {lista,erro}=useAvisos(),[falha,setFalha]=useState(''),[status,setStatus]=useState(''),[ocupado,setOcupado]=useState(false),navigate=useNavigate();const executar=async f=>{setOcupado(true);setFalha('');setStatus('');try{await f()}catch(e){setFalha(e.message)}finally{setOcupado(false)}};return <div className="comercial-page"><header className="admin-cabecalho"><span className="admin-eyebrow">ACOMPANHAMENTO</span><h1>Seus avisos</h1><p>Propostas, mensagens, artes e provas. Ative o push para receber avisos também quando esta página estiver fechada.</p></header><section className="card card-pad"><h2>Notificações neste dispositivo</h2><p>O navegador pedirá sua autorização. Ative em cada computador ou celular que você utiliza. No iPhone/iPad, adicione o site à Tela de Início e abra por esse ícone para ativar o push. Ao sair da conta, o recebimento neste dispositivo é desativado.</p><div className="row"><button className="btn btn-primary" disabled={ocupado||!suportaPush()} onClick={()=>executar(async()=>{await ativarPush();const r=await executarComercial('notificacoesUsuario',{acao:'teste'});setStatus(r.entrega==='entregue'?'Push ativado. O teste foi aceito pelo serviço do navegador; confira a notificação neste dispositivo.':'Push cadastrado. A entrega do teste está pendente; você ainda pode consultar os avisos aqui.')})}>Ativar e testar push</button><button className="btn" disabled={ocupado} onClick={()=>executar(async()=>{await desativarPush();setStatus('Push desativado neste dispositivo.')})}>Desativar push</button></div>{!suportaPush()&&<p>Push não está disponível neste navegador. Seu histórico de avisos continua abaixo.</p>}{status&&<p role="status">{status}</p>}{(falha||erro)&&<p role="alert">{falha||erro}</p>}</section><div className="row" style={{margin:'20px 0'}}><h2>Atualizações recentes</h2><button className="btn" disabled={ocupado||!lista.some(n=>!n.lida)} onClick={()=>executar(()=>executarComercial('notificacoesUsuario',{acao:'ler',ids:lista.filter(n=>!n.lida).map(n=>n.id)}))}>Marcar todas como lidas</button></div><div className="artes-lista">{!lista.length&&<p>Nenhum aviso por enquanto.</p>}{lista.map(n=><button className="card card-pad" style={{textAlign:'left',borderColor:n.lida?undefined:'var(--brand-green)'}} key={n.id} onClick={()=>executar(async()=>{await executarComercial('notificacoesUsuario',{acao:'ler',ids:[n.id]});navigate(n.url?.startsWith('/')&&!n.url.startsWith('//')?n.url:'/notificacoes')})}><strong>{!n.lida?'● ':''}{n.titulo}</strong><p>{n.corpo}</p><small>{n.criadoEm?.toDate?.().toLocaleString('pt-BR')}</small></button>)}</div></div>}
