import {useEffect,useState} from 'react'
import {Link} from 'react-router-dom'
import {useAuth} from '../store/AuthContext.jsx'
import {listarPropostasGestao,executarComercial} from '../lib/comercial.js'
import FiltrosPropostas,{filtrosConsulta} from '../components/FiltrosPropostas.jsx'
import {filtrarPropostas,propostasValidas,linhasQuantidades,agruparQuantidades,agruparFinanceiro,normalizar,financeiro,recebimentosHistoricos,ROTULOS_STATUS} from '../../functions/relatorios.mjs'
import {fmtBRL} from '../lib/glb/precos.js'
import {exportarRelatorio} from '../lib/exportarRelatorio.js'
const n=v=>v.toLocaleString('pt-BR',{maximumFractionDigits:2,minimumFractionDigits:2})

export default function Relatorios(){
  const {ehAdmin}=useAuth(),[lista,setLista]=useState(null),[retiradas,setRetiradas]=useState([]),[filtros,setFiltros]=useState({}),[modo,setModo]=useState('aprovadas'),[por,setPor]=useState('cliente'),[categoria,setCategoria]=useState(''),[cor,setCor]=useState(''),[buscaMaterial,setBuscaMaterial]=useState(''),[detalhado,setDetalhado]=useState(false),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false),[conferencia,setConferencia]=useState(false)
  async function carregar(){setOcupado(true);setErro('');try{const [p,r]=await Promise.all([listarPropostasGestao(),listarPropostasGestao({excluidas:true})]);setLista(p);setRetiradas(r)}catch(e){setErro(e.message)}finally{setOcupado(false)}}
  useEffect(()=>{carregar()},[])
  const atuais=propostasValidas(lista||[],modo),selecionadas=filtrarPropostas(atuais,filtrosConsulta(filtros));
  const pagamentosRetirados=filtrarPropostas(recebimentosHistoricos([...(lista||[]),...retiradas]),{...filtros,status:filtros.pagamento||''}),recebidoRetiradas=pagamentosRetirados.reduce((t,p)=>t+financeiro(p).recebido,0),financeiras=[...selecionadas,...pagamentosRetirados.map(p=>({...p,historicoFinanceiro:true}))];
  const fin=agruparFinanceiro(financeiras,por),totais=financeiras.reduce((t,p)=>{const f=financeiro(p);for(const k of ['proposto','aprovado','recebido'])t[k]+=f[k];return t},{proposto:0,aprovado:0,recebido:0})
  const todasLinhas=selecionadas.flatMap(linhasQuantidades),linhas=todasLinhas.filter(l=>(!categoria||l.categoria===categoria)&&(!cor||l.cor===cor)&&normalizar([l.item,l.material,l.cor,l.codigo].join(' ')).includes(normalizar(buscaMaterial))),grupos=agruparQuantidades(linhas),pendencias=linhas.filter(l=>l.quantidade==null).length,categorias=[...new Set(todasLinhas.map(l=>l.categoria))].sort(),cores=[...new Set(todasLinhas.filter(l=>!categoria||l.categoria===categoria).map(l=>l.cor).filter(Boolean))].sort()
  const totaisUnidade=linhas.reduce((r,l)=>{if(l.quantidade!=null)r[l.unidade]=(r[l.unidade]||0)+l.quantidade;return r},{});
  const antigas=selecionadas.filter(p=>p.levantamentoSugerido&&(p.manifestoProducao?.materiais||[]).some(s=>!s.quantitativo))
  const contexto=[modo==='aprovadas'?'Somente estandes aprovados e liberados para produção':'Última versão válida por cliente/feira; inclui propostas ainda não aprovadas',...['feira','organizadora','cliente'].map(k=>filtros[k]?`${k}: ${selecionadas[0]?.[k==='cliente'?'clienteNome':k==='organizadora'?'organizadoraNome':'feira']||filtros[k]}`:null),filtros.busca?`Busca: ${filtros.busca}`:null,...[filtros.comercial,filtros.arte,filtros.pagamento].filter(Boolean).map(s=>ROTULOS_STATUS[s]||s),categoria,cor,buscaMaterial?`Material: ${buscaMaterial}`:null,`${selecionadas.length} estande(s); ${pendencias} medida(s) pendente(s). Áreas líquidas, sem perdas de corte.`].filter(Boolean).join(' | ')
  async function exportar(tipo,quantidades){setErro('');setOcupado(true);try{const colunas=quantidades?(detalhado?['Cliente','Feira','Organizadora','Localização','Categoria','Item','Material','Cor','Código','Unidade','Quantidade']:['Categoria','Material','Cor','Código','Unidade','Quantidade medida','Medidas pendentes','Estandes']):['Agrupamento','Estandes','Proposto (R$)','Aprovado (R$)','Recebido registrado (R$)'];const linhasExport=quantidades?(detalhado?linhas.map(l=>[l.cliente,l.feira,l.organizadora,l.localizacao,l.categoria,l.item,l.material,l.cor,l.codigo||'',l.unidade,l.quantidade==null?'PENDENTE':n(l.quantidade)]):grupos.map(g=>[g.categoria,g.material,g.cor,g.codigo||'',g.unidade,n(g.quantidade),g.pendencias,g.estandes])):fin.map(g=>[g.nome,g.propostas,n(g.proposto),n(g.aprovado),n(g.recebido)]);await exportarRelatorio({tipo,titulo:quantidades?'Quantidades de materiais e mobiliário':'Relatório financeiro',contexto,colunas,linhas:linhasExport,nome:quantidades?'uset-quantidades':'uset-financeiro'})}catch(e){setErro(e.message)}finally{setOcupado(false)}}
  async function confirmar(){setOcupado(true);setErro('');try{for(let i=0;i<antigas.length;i+=40)await executarComercial('confirmarQuantitativos',{propostas:antigas.slice(i,i+40).map(p=>({id:p.id,modeloVersao:p.levantamentoSugerido.modeloVersao}))});setConferencia(false);await carregar()}catch(e){setErro(e.message)}finally{setOcupado(false)}}
  return <div className="admin-pagina"><header className="admin-cabecalho"><span className="admin-eyebrow">PLANEJAMENTO E FINANCEIRO</span><h1>Relatórios</h1><p>Valores e quantidades por cliente, feira e organizadora. O mobiliário e os materiais originais também entram no levantamento.</p><button className="btn" disabled={ocupado} onClick={carregar}>Atualizar dados</button></header>{erro&&<p className="erro-inline" role="alert">{erro}</p>}{!lista&&!erro&&<p role="status">Carregando relatórios…</p>}
    <section className="card card-pad"><label>Base do relatório<select className="select" value={modo} onChange={e=>setModo(e.target.value)}><option value="aprovadas">Somente aprovadas e liberadas para produção</option><option value="todas">Última versão válida, incluindo em análise</option></select></label><p>Propostas substituídas e retiradas não geram quantidades. Cada cliente/feira aparece uma vez. Os valores representam personalizações e adicionais; não incluem o preço do pacote original.</p></section>
    <FiltrosPropostas lista={lista||[]} filtros={filtros} aoMudar={setFiltros}/><p aria-live="polite">{selecionadas.length} estande(s) selecionado(s)</p>
    <div className="propostas-resumo">{[['proposto','Valor proposto'],['aprovado','Valor aprovado comercialmente'],['recebido','Recebido registrado']].map(([k,t])=><div className="card card-pad" key={k}><span>{t}</span><strong>{fmtBRL(totais[k])}</strong></div>)}</div><p className="dim">Proposta aprovada não significa pagamento recebido. Recebimentos dependem do registro da cobrança e incluem o histórico de retiradas/substituições deste filtro; pagamentos feitos fora da plataforma não são inferidos.</p>
    <section className="card card-pad"><h2>Financeiro</h2><label>Agrupar por<select className="select" value={por} onChange={e=>setPor(e.target.value)}><option value="cliente">Cliente</option><option value="feira">Feira</option><option value="organizadora">Organizadora</option></select></label><div className="relatorio-tabela"><table><thead><tr><th>{por==='cliente'?'Cliente':por==='feira'?'Feira':'Organizadora'}</th><th>Estandes</th><th>Proposto</th><th>Aprovado</th><th>Recebido registrado</th></tr></thead><tbody>{fin.map(g=><tr key={`${por}:${g.chave}`}><td>{g.nome}</td><td>{g.propostas}</td><td>{fmtBRL(g.proposto)}</td><td>{fmtBRL(g.aprovado)}</td><td>{fmtBRL(g.recebido)}</td></tr>)}</tbody></table></div><div className="row"><button className="btn" disabled={ocupado||!fin.length} onClick={()=>exportar('csv',false)}>Baixar financeiro CSV</button><button className="btn" disabled={ocupado||!fin.length} onClick={()=>exportar('pdf',false)}>Baixar financeiro PDF</button></div></section>
    {!!pagamentosRetirados.length&&<details className="card card-pad"><summary>Histórico financeiro de retiradas e substituições · {pagamentosRetirados.length} · {fmtBRL(recebidoRetiradas)} recebido registrado</summary><p>Esses recebimentos estão incluídos no total financeiro e ficam preservados para conciliação. Não compõem valores aprovados nem materiais a produzir. A retirada não realiza estorno.</p>{pagamentosRetirados.map(p=><p key={p.id}>{p.clienteNome} · {p.feira} · {fmtBRL(financeiro(p).recebido)} · {p.pagamento.status}</p>)}</details>}
    <section className="card card-pad"><h2>Materiais, artes e mobiliário</h2><p>Exemplo: selecione a feira, escolha “Carpete” e depois a cor azul. O total será a soma das áreas medidas dos estandes desta seleção.</p><div className="propostas-filtros"><label>Categoria<select className="select" value={categoria} onChange={e=>{setCategoria(e.target.value);setCor('')}}><option value="">Todas as categorias</option>{categorias.map(c=><option key={c}>{c}</option>)}</select></label><label>Cor / referência<select className="select" value={cor} onChange={e=>setCor(e.target.value)}><option value="">Todas as cores</option>{cores.map(c=><option key={c}>{c}</option>)}</select></label><label>Material ou item<input className="input" type="search" value={buscaMaterial} placeholder="Ex.: azul, napa, bistrô" onChange={e=>setBuscaMaterial(e.target.value)}/></label><label>Detalhamento<select className="select" value={detalhado?'sim':'nao'} onChange={e=>setDetalhado(e.target.value==='sim')}><option value="nao">Totais por material e cor</option><option value="sim">Detalhado por estande e item</option></select></label></div>
    <p className="orientacao"><strong>Total da seleção: {Object.entries(totaisUnidade).map(([u,v])=>`${n(v)} ${u}`).join(' · ')||'Nenhuma quantidade medida'}</strong>{pendencias?` · ${pendencias} medida(s) pendente(s)`:''}</p>{!!pendencias&&<p className="orientacao" role="status">{pendencias} medida(s) pendente(s): os totais conhecidos são parciais. Medidas sem conferência não são consideradas zero.</p>}{ehAdmin&&<p>As metragens e cores originais são cadastradas em <Link to="/precos">Preços → Quantidades e materiais para relatórios</Link>. Os nomes das cores personalizados vêm do catálogo escolhido pelo cliente.</p>}
    {ehAdmin&&!!antigas.length&&<button className="btn" disabled={ocupado} onClick={()=>setConferencia(!conferencia)}>Conferir levantamento de {antigas.length} proposta(s) antiga(s)</button>}{conferencia&&<div className="orientacao"><h3>Confira antes de aplicar às propostas antigas</h3><p>Estes dados vêm do mapeamento atual dos projetos. Confirme que correspondem aos arquivos dessas propostas. A conferência ficará registrada, sem mudar escolhas ou preços.</p><div className="relatorio-tabela"><table><thead><tr><th>Cliente / projeto</th><th>Material</th><th>Cor</th><th>Área líquida</th></tr></thead><tbody>{antigas.flatMap(p=>(p.manifestoProducao.materiais||[]).filter(s=>!s.quantitativo).map(s=>{const q=p.levantamentoSugerido.quantitativos[s.id];return <tr key={p.id+s.id}><td>{p.clienteNome} · {p.modeloNome} · {s.nome}</td><td>{q.categoria} · {q.material}</td><td>{q.cor}</td><td>{q.areaM2==null?'Pendente':`${n(q.areaM2)} m²`}</td></tr>}))}</tbody></table></div><button className="btn btn-primary" disabled={ocupado} onClick={confirmar}>Confirmar medidas e atualizar relatórios</button></div>}
    <div className="relatorio-tabela"><table><thead><tr>{(detalhado?['Cliente / feira','Item','Categoria','Material / cor','Quantidade']:['Categoria','Material / cor','Quantidade medida','Pendências','Estandes']).map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{detalhado?linhas.map((l,i)=><tr key={i}><td>{l.cliente}<br/>{l.feira} · {l.localizacao}</td><td>{l.item}</td><td>{l.categoria}</td><td>{l.material} · {l.cor} {l.codigo}</td><td>{l.quantidade==null?'Pendente':`${n(l.quantidade)} ${l.unidade}`}</td></tr>):grupos.map((g,i)=><tr key={i}><td>{g.categoria}</td><td>{g.material} · {g.cor} {g.codigo}</td><td>{n(g.quantidade)} {g.unidade}{g.pendencias?' (parcial)':''}</td><td>{g.pendencias}</td><td>{g.estandes}</td></tr>)}</tbody></table></div>{!linhas.length&&<p>Nenhum material corresponde à seleção.</p>}<p className="dim">Áreas líquidas do mapeamento, sem perdas de corte. Artes contam a área inteira, inclusive a franquia do pacote. Logos são contados por unidade. Um conjunto cadastrado como bistrô com banquetas é contado como conjunto.</p><div className="row"><button className="btn" disabled={ocupado||!linhas.length} onClick={()=>exportar('csv',true)}>Baixar quantidades CSV</button><button className="btn" disabled={ocupado||!linhas.length} onClick={()=>exportar('pdf',true)}>Baixar quantidades PDF</button></div></section>
  </div>
}
