import {useEffect,useState} from 'react'
import {collection,onSnapshot} from 'firebase/firestore'
import {ref,uploadBytesResumable} from 'firebase/storage'
import {db,storage} from '../lib/firebase.js'
import {executarComercial} from '../lib/comercial.js'
import ArquivoProducao from './ArquivoProducao.jsx'
export default function ArquivosApoio({propostaId,papel,prazoVencido}){
 const [arquivos,setArquivos]=useState([]),[categoria,setCategoria]=useState('logo'),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false),[progresso,setProgresso]=useState(0)
 useEffect(()=>onSnapshot(collection(db,'artesPropostas',propostaId,'apoio'),s=>setArquivos(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.enviadoEm?.seconds||0)-(a.enviadoEm?.seconds||0))),e=>setErro(e.message)),[propostaId])
 const enviar=async f=>{setOcupado(true);setErro('');setProgresso(0);try{const bytes=new Uint8Array(await f.slice(0,8192).arrayBuffer()),txt=new TextDecoder().decode(bytes).replace(/^\uFEFF/,'').trimStart(),ext=f.name.split('.').at(-1).toLowerCase(),mime=txt.startsWith('%PDF-')?'application/pdf':txt.startsWith('%!PS')?'application/postscript':ext==='svg'?'image/svg+xml':bytes[0]===137&&bytes[1]===80?'image/png':bytes[0]===255&&bytes[1]===216?'image/jpeg':null;if(!mime||!['pdf','ai','eps','svg','png','jpg','jpeg'].includes(ext)||f.size>30*1024*1024)throw Error('Envie PDF, AI salvo como PDF, EPS, SVG, PNG ou JPG de até 30 MB.');const r=await executarComercial('artesProposta',{acao:'reservarApoio',propostaId,categoria,nome:f.name,bytes:f.size,mime});await new Promise((resolve,reject)=>{const tarefa=uploadBytesResumable(ref(storage,r.caminho),f,{contentType:mime});tarefa.on('state_changed',s=>setProgresso(Math.round(s.bytesTransferred/s.totalBytes*100)),reject,resolve)});await executarComercial('artesProposta',{acao:'enviarApoio',propostaId,uploadId:r.uploadId})}catch(e){setErro(e.message)}finally{setOcupado(false)}}
 return <section className="card card-pad"><h2>Arquivos de apoio da marca</h2><p>Envie logos vetorizados, manual de marca e referências. Esses arquivos não precisam ter o tamanho da parede e não substituem a arte final de impressão.</p>{papel==='expositor'&&!prazoVencido&&<fieldset disabled={ocupado}><label>Tipo de material<select className="select" value={categoria} onChange={e=>setCategoria(e.target.value)}><option value="logo">Logo vetorizado</option><option value="manual">Manual de marca</option><option value="referencia">Referência / outro material</option></select></label><label className="arte-escolher">Enviar arquivo de apoio<input type="file" accept=".pdf,.ai,.eps,.svg,.png,.jpg,.jpeg" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)enviar(f)}}/></label><p className="dim">PDF, AI compatível com PDF, EPS, SVG, PNG ou JPG · até 30 MB por arquivo. EPS e SVG ficam disponíveis para download.</p></fieldset>}{ocupado&&<progress aria-label="Enviando arquivo" max="100" value={progresso}/>}<div>{arquivos.map(a=><ArquivoProducao key={a.id} arquivo={a.arquivo} titulo={({logo:'Logo vetorizado',manual:'Manual de marca',referencia:'Referência'})[a.categoria]}/>)}</div>{erro&&<p role="alert">{erro}</p>}</section>
}
