import {useEffect,useState,useRef} from 'react'
import {getBlob,ref,uploadBytes} from 'firebase/storage'
import {storage} from '../lib/firebase.js'
import {operacao,ehGestor} from '../lib/operacao.js'
import {STATUS_PENDENCIAS,permissoesPendencia} from '../lib/pendencias.js'
import {baixarPrivado} from '../lib/producao/envio.js'
export function FotoOperacional({arquivo}){
  const [url,setUrl]=useState(''),[erro,setErro]=useState(''),dialogo=useRef(null)
  useEffect(()=>{let vivo=true,u;getBlob(ref(storage,arquivo.caminho)).then(b=>{u=URL.createObjectURL(b);if(vivo)setUrl(u);else URL.revokeObjectURL(u)}).catch(()=>{if(vivo)setErro('Foto indisponível')});return()=>{vivo=false;if(u)URL.revokeObjectURL(u)}},[arquivo.caminho])
  return url?<><button type="button" className="operacao-foto-miniatura" aria-label={`Ampliar ${arquivo.nome||'foto'}`} onClick={()=>dialogo.current.showModal()}><img src={url} alt={arquivo.nome||'Foto do serviço'}/></button><dialog ref={dialogo} className="operacao-foto-dialogo"><button type="button" className="btn" onClick={()=>dialogo.current.close()}>Fechar foto</button><img src={url} alt={arquivo.nome||'Foto do serviço'}/><button type="button" className="btn" onClick={async()=>{try{await baixarPrivado(arquivo)}catch(e){setErro(e.message)}}}>Salvar / compartilhar foto</button>{erro&&<p role="alert">{erro}</p>}</dialog></>:<span>{erro||'Carregando foto…'}</span>
}
function Fotos({lista=[]}){return <div className="operacao-fotos">{lista.map(f=><FotoOperacional key={f.caminho} arquivo={f}/>)}</div>}
const vazio={descricao:'',equipeId:'',prioridade:'normal',origem:'equipe',responsavel:'',itens:[]}
export default function PendenciasOperacionais({ordem,perfil,pendencias,equipes,usuarios=[],aoAtualizar}){
  const [form,setForm]=useState(vazio),[fotos,setFotos]=useState([]),[erro,setErro]=useState(''),[ocupado,setOcupado]=useState(false),[acao,setAcao]=useState(null),[nota,setNota]=useState(''),[orientacao,setOrientacao]=useState(''),[fotosFim,setFotosFim]=useState([]),[filtro,setFiltro]=useState(''),[busca,setBusca]=useState(''),[selecionadas,setSelecionadas]=useState([]),[produtores,setProdutores]=useState(ordem.produtorIds||[]),[atendimento,setAtendimento]=useState(ordem.atendimentoIds||[])
  const permissoes=permissoesPendencia(perfil,ordem),gestor=ehGestor(perfil)
  useEffect(()=>{setProdutores(ordem.produtorIds||[]);setAtendimento(ordem.atendimentoIds||[])},[ordem.produtorIds,ordem.atendimentoIds])
  const chamar=d=>operacao({...d,ordemId:ordem.id,revisao:ordem.revisao})
  async function tarefa(fn){setOcupado(true);setErro('');try{await fn();aoAtualizar?.();return true}catch(e){if(e.arquivosRestantes){setFotosFim(e.arquivosRestantes);if(e.fase==='abertura')setAcao({id:e.pendenciaId,status:'foto_abertura'})}setErro(e.message);return false}finally{setOcupado(false)}}
  async function enviarFotos(id,arquivos,fase){for(let i=0;i<arquivos.length;i++){const f=arquivos[i];try{const r=await chamar({acao:'reservarFotoPendencia',id,fase,bytes:f.size,mime:f.type,nome:f.name});await uploadBytes(ref(storage,r.caminho),f,{contentType:f.type});await chamar({acao:'anexarFotoPendencia',id,fase,uploadId:r.uploadId})}catch(e){throw Object.assign(e,{arquivosRestantes:arquivos.slice(i),pendenciaId:id,fase})}}}
  async function criar(e){e.preventDefault();let criada;const ok=await tarefa(async()=>{criada=await chamar({acao:'pendencia',...form});setForm(vazio);await enviarFotos(criada.id,fotos,'abertura');setFotos([])});if(!ok&&criada){setFotos([]);setErro('A pendência foi criada. O envio de fotos não terminou; confira as fotos registradas antes de reenviar.')}}
  const lista=pendencias.filter(a=>(!filtro||a.status===filtro)&&`${a.descricao} ${a.equipeNome} ${a.responsavel}`.toLowerCase().includes(busca.toLowerCase()))
  const escolher=(a,status)=>{setAcao({...a,status});setNota(status==='editar'?a.descricao:'');setFotosFim([]);setErro('')}
  const inputFotos=(set,valor)=><><label className="btn">Selecionar fotos<input hidden type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={ocupado} onChange={e=>set([...valor,...Array.from(e.target.files||[])].slice(0,12))}/></label><label className="btn">Tirar foto<input hidden type="file" accept="image/*" capture="environment" disabled={ocupado} onChange={e=>set([...valor,...Array.from(e.target.files||[])].slice(0,12))}/></label>{valor.length>0&&<p>{valor.length} foto(s) selecionada(s) <button type="button" className="btn btn-sm" onClick={()=>set([])}>Limpar seleção</button></p>}</>
  return <>
    {gestor&&<details className="card card-pad operacao-acordeao"><summary>Responsáveis pelo estande</summary>{[['produtor','Produtores',produtores,setProdutores],['atendimento_comercial','Atendimento comercial',atendimento,setAtendimento]].map(([papel,titulo,ids,set])=><div key={papel}><h3>{titulo}</h3>{usuarios.filter(u=>u.papel===papel&&u.ativo!==false&&u.feiraIds?.includes(ordem.feiraId)).map(u=><label className="operacao-check" key={u.uid}><input type="checkbox" checked={ids.includes(u.uid)} onChange={e=>set(e.target.checked?[...ids,u.uid]:ids.filter(x=>x!==u.uid))}/>{u.nome||u.email}</label>)}</div>)}<button className="btn btn-primary" disabled={ocupado} onClick={()=>tarefa(()=>chamar({acao:'atribuirResponsaveis',produtorIds:produtores,atendimentoIds:atendimento}))}>Salvar responsáveis</button></details>}
    <section className="card card-pad"><h2>Pendências e execução</h2>{erro&&<p role="alert">{erro}</p>}
      {permissoes.criar&&<details className="operacao-acordeao"><summary>Abrir pendência</summary><form className="col" onSubmit={criar}><label>Serviço ou ajuste<textarea required className="input" maxLength={2000} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label>Equipe<select required className="select" value={form.equipeId} onChange={e=>setForm({...form,equipeId:e.target.value})}><option value="">Selecione</option>{equipes.filter(e=>e.ativo&&ordem.equipeIds.includes(e.id)&&(perfil.papel!=='equipe_producao'||perfil.equipeIds?.includes(e.id))&&(perfil.papel!=='mobiliario'||e.especialidade==='mobiliario')&&(perfil.papel!=='analista_cv'||e.especialidade==='cv')).map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></label><label>Responsável<input className="input" maxLength={180} value={form.responsavel} onChange={e=>setForm({...form,responsavel:e.target.value})}/></label><label>Prioridade<select className="select" value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})}>{['baixa','normal','alta','urgente'].map(x=><option key={x}>{x}</option>)}</select></label><label>Solicitado por<select className="select" value={form.origem} onChange={e=>setForm({...form,origem:e.target.value})}><option value="equipe">Equipe</option><option value="cliente">Cliente</option><option value="organizadora">Organizadora · exige aprovação</option></select></label>{form.equipeId&&equipes.find(e=>e.id===form.equipeId)?.especialidade==='mobiliario'&&<details><summary>Relacionar mobiliário da proposta</summary>{[...(ordem.manifesto?.moveis||[]),...(ordem.manifesto?.extras||[])].map(a=><label className="operacao-check" key={a.id}><input type="checkbox" checked={form.itens.includes(a.id)} onChange={e=>setForm({...form,itens:e.target.checked?[...form.itens,a.id]:form.itens.filter(x=>x!==a.id)})}/>{a.nome}</label>)}</details>}<div>{inputFotos(setFotos,fotos)}</div><button className="btn btn-primary" disabled={ocupado}>Registrar pendência</button></form></details>}
      <div className="admin-filtros"><label>Situação<select className="select" value={filtro} onChange={e=>setFiltro(e.target.value)}><option value="">Todas</option>{Object.entries(STATUS_PENDENCIAS).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label><label>Buscar<input className="input" value={busca} onChange={e=>setBusca(e.target.value)}/></label></div>
      {gestor&&selecionadas.length>0&&<button className="btn btn-primary" disabled={ocupado} onClick={()=>tarefa(()=>chamar({acao:'validarLote',ids:selecionadas})).then(ok=>{if(ok)setSelecionadas([])})}>Validar {selecionadas.length} selecionada(s)</button>}
      {!lista.length&&<p>Nenhuma pendência neste filtro.</p>}{lista.map(a=>{const m=permissoesPendencia(perfil,ordem,a),atual=a.revisao===ordem.revisao;return <details className="admin-item operacao-acordeao" key={a.id}><summary>{a.descricao}</summary><p>{a.equipeNome||equipes.find(e=>e.id===a.equipeId)?.nome} · {STATUS_PENDENCIAS[a.status]} · {a.prioridade||'normal'} · revisão {a.revisao}</p><p>Origem: {a.origem||'equipe'} · responsável: {a.responsavel||'A definir'} · registrado por {a.autorNome||a.autor}</p>{a.executadoNome&&<p>Executado por {a.executadoNome} · {a.notaExecucao}</p>}{a.validadoNome&&<p>Validado por {a.validadoNome}{a.validacaoAutomatica?' (validação automática habilitada para a feira)':''} · {a.notaValidacao}</p>}{a.nota&&<p>Última observação: {a.nota}</p>}<h4>Fotos da abertura</h4><Fotos lista={a.fotos}/><h4>Fotos da execução</h4><Fotos lista={a.fotosConclusao}/>{!atual?<p>Registro anterior. Abra uma pendência na revisão atual se necessário.</p>:<div className="operacao-acoes">{m.editar&&<button className="btn" onClick={()=>escolher(a,'editar')}>Editar pendência</button>}{m.editar&&<button className="btn" onClick={()=>escolher(a,'foto_abertura')}>Adicionar fotos</button>}{a.status==='aguardando_aprovacao'&&m.aprovar&&<><button className="btn" onClick={()=>escolher(a,'aberta')}>Aprovar solicitação</button><button className="btn" onClick={()=>escolher(a,'recusada')}>Recusar solicitação</button></>}{a.status==='aberta'&&m.executar&&<button className="btn" disabled={ocupado} onClick={()=>tarefa(()=>chamar({acao:'pendencia',id:a.id,status:'em_execucao'}))}>Iniciar execução</button>}{a.status==='em_execucao'&&m.executar&&<button className="btn btn-primary" onClick={()=>escolher(a,'aguardando_validacao')}>Registrar execução</button>}{a.status==='aguardando_validacao'&&m.validar&&<><button className="btn btn-primary" onClick={()=>escolher(a,'concluida')}>Validar execução</button><label className="operacao-check"><input type="checkbox" checked={selecionadas.includes(a.id)} onChange={e=>setSelecionadas(e.target.checked?[...selecionadas,a.id].slice(0,30):selecionadas.filter(x=>x!==a.id))}/>Selecionar para validação em lote</label></>}{['aguardando_validacao','concluida'].includes(a.status)&&m.validar&&<button className="btn" onClick={()=>escolher(a,'aberta')}>Reabrir / solicitar ajuste</button>}</div>}</details>})}
      {acao&&<form className="card card-pad col" onSubmit={e=>{e.preventDefault();tarefa(async()=>{if(acao.status==='editar')await chamar({acao:'pendencia',id:acao.id,editar:true,descricao:nota,responsavel:acao.responsavel,prioridade:acao.prioridade,equipeId:acao.equipeId});else {await enviarFotos(acao.id,fotosFim,acao.status==='foto_abertura'?'abertura':'conclusao');setFotosFim([]);if(acao.status!=='foto_abertura')await chamar({acao:'pendencia',id:acao.id,status:acao.status,nota})}setAcao(null)})}}><h3>{acao.status==='editar'?'Editar descrição':acao.status==='foto_abertura'?'Adicionar fotos':STATUS_PENDENCIAS[acao.status]}</h3><label>{acao.status==='editar'?'Nova descrição':'Observação / motivo'}<textarea className="input" maxLength={2000} required={acao.status==='editar'||acao.status==='recusada'||acao.status==='aberta'} value={nota} onChange={e=>setNota(e.target.value)}/></label>{acao.status==='editar'&&<><label>Responsável<input className="input" value={acao.responsavel||''} onChange={e=>setAcao({...acao,responsavel:e.target.value})}/></label><label>Prioridade<select className="select" value={acao.prioridade||'normal'} onChange={e=>setAcao({...acao,prioridade:e.target.value})}>{['baixa','normal','alta','urgente'].map(x=><option key={x}>{x}</option>)}</select></label>{gestor&&<label>Equipe responsável<select className="select" value={acao.equipeId} onChange={e=>setAcao({...acao,equipeId:e.target.value})}>{equipes.filter(e=>e.ativo&&ordem.equipeIds.includes(e.id)).map(e=><option key={e.id} value={e.id}>{e.nome}</option>)}</select></label>}</>}{['aguardando_validacao','foto_abertura'].includes(acao.status)&&<div>{inputFotos(setFotosFim,fotosFim)}<p>Fotos opcionais, até 12 por etapa. A execução será enviada para validação.</p></div>}<div className="operacao-acoes"><button className="btn btn-primary" disabled={ocupado}>Confirmar registro</button><button type="button" className="btn" disabled={ocupado} onClick={()=>setAcao(null)}>Cancelar</button></div></form>}
    </section>
    {(permissoes.anotar||gestor||perfil.papel==='produtor')&&<section className="card card-pad"><h2>Orientações e montagem</h2><p>Montagem: {({em_montagem:'Em montagem',aguardando_validacao:'Aguarda validação do gerente',concluida:'Concluída'})[ordem.montagemStatus]||'Em montagem'}</p>{ordem.montagemAutorNome&&<p>{ordem.montagemAutorNome} · {ordem.montagemNota}</p>}<label>Orientação ou observação<textarea className="input" value={orientacao} onChange={e=>setOrientacao(e.target.value)} maxLength={4000}/></label><div className="operacao-acoes">{permissoes.anotar&&<button className="btn" disabled={ocupado||!orientacao.trim()} onClick={()=>tarefa(()=>chamar({acao:'notaAnalista',nota:orientacao})).then(ok=>{if(ok)setOrientacao('')})}>Registrar orientação</button>}{(gestor||perfil.papel==='produtor')&&ordem.montagemStatus!=='concluida'&&<button className="btn btn-primary" disabled={ocupado} onClick={()=>tarefa(()=>chamar({acao:'concluirEstande',nota:orientacao}))}>{gestor?'Validar montagem do estande':'Montagem pronta · solicitar validação'}</button>}{gestor&&ordem.montagemStatus==='concluida'&&<button className="btn" disabled={ocupado||!orientacao.trim()} onClick={()=>tarefa(()=>chamar({acao:'concluirEstande',reabrir:true,nota:orientacao}))}>Reabrir montagem</button>}</div></section>}
  </>
}
