import {useRef,useState} from 'react'
import Viewer,{useGLB} from './Viewer.jsx'
import {ref,uploadBytes} from 'firebase/storage'
import {storage} from '../lib/firebase.js'
import {operacao} from '../lib/operacao.js'
import {salvarBlob} from '../lib/baixarArquivo.js'
const VISTAS=[['frente','Frente'],['esquerda','Elevação lateral'],['cima','Planta baixa'],['perspectiva','Isométrica']]
export default function VistasProducao({arquivo,ordemId,revisao,podeSalvar}){
  const {cena,erro,carregando}=useGLB(arquivo?.url||''),capturasRef=useRef(null),[vista,setVista]=useState('frente'),[imagens,setImagens]=useState([]),[ocupado,setOcupado]=useState(false),[mensagem,setMensagem]=useState('')
  async function gerar(salvar=false){setMensagem('');setOcupado(true);try{const fotos=capturasRef.current?.()||[];if(fotos.length!==4)throw Error('Aguarde o carregamento do projeto para gerar as vistas.');setImagens(fotos);if(salvar){for(const foto of fotos){const blob=await(await fetch(foto.url)).blob(),nome=`Vista ${foto.nome} - revisão ${revisao}.jpg`,r=await operacao({acao:'reservarAnexo',tipo:'ordensProducao',parentId:ordemId,bytes:blob.size,mime:'image/jpeg',nome,revisao});await uploadBytes(ref(storage,r.caminho),blob,{contentType:'image/jpeg'});await operacao({acao:'anexar',tipo:'ordensProducao',parentId:ordemId,uploadId:r.uploadId})}setMensagem('As quatro vistas foram anexadas à ordem de produção.')}}catch(e){setMensagem(e.message)}finally{setOcupado(false)}}
  return <section className="card card-pad"><h2>Projeto aprovado · revisão {revisao}</h2><p>Consulta 3D e vistas de montagem. A frente corresponde ao eixo frontal do projeto; confira a orientação no mapeamento. Imagens sem cotas técnicas.</p>{carregando&&<p role="status">Carregando GLB…</p>}{erro&&<p role="alert">Não foi possível abrir o GLB. Os documentos anexados continuam disponíveis.</p>}<div className="operacao-acoes">{VISTAS.map(([id,n])=><button className="btn" key={id} onClick={()=>setVista(id)}>{n}</button>)}</div><div className="operacao-3d"><Viewer cena={cena} vista={vista} aoAplicarVista={()=>setVista(null)} capturasRef={capturasRef} capturasProducao/></div><div className="operacao-acoes"><button className="btn" disabled={!cena||ocupado} onClick={()=>gerar()}>Gerar quatro vistas</button>{podeSalvar&&<button className="btn btn-primary" disabled={!cena||ocupado} onClick={()=>gerar(true)}>Gerar e anexar vistas à produção</button>}</div>{mensagem&&<p role="status">{mensagem}</p>}<div className="operacao-vistas">{imagens.map(f=><figure key={f.nome}><img src={f.url} alt={f.nome}/><figcaption>{f.nome}</figcaption><button className="btn btn-sm" onClick={async()=>{try{await salvarBlob(await(await fetch(f.url)).blob(),`${f.nome}.jpg`)}catch(e){setMensagem(e.message)}}}>Baixar vista</button></figure>)}</div></section>
}
